FROM python:3.10.11-slim-buster

# Set Mlflow URI
ENV MLFLOWTRACKINGURI=sqlite:///mlruns.db

WORKDIR /app
COPY . /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY .kaggle/kaggle.json /root/.kaggle/
RUN chmod 600 /root/.kaggle/kaggle.json

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run"]
CMD ["apps/trainingapp.py"]
