version: '3.8'

services:
  db:
    restart: always
    image: mysql/mysql-server:8.0
    container_name: mlflow_db
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mlruns:/var/lib/mysql
        
  frauddetectionapp:
    image: app_acr:latest
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
      # - ./.kaggle/kaggle.json:/root/.kaggle/kaggle.json
    environment:
      - MLFOW_TRACKING_URI_MYSQL=mysql+pymysql://admin:Sun1moon2@localhost:3306/db.db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow_server:latest
    container_name: mlflow_server
    ports:
      - "8080:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - MLFOW_TRACKING_URI_MYSQL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@localhost:3306/${MYSQL_DATABASE}
      # - mysql+pymysql://admin:Sun1moon2@localhost:3306/db
      # - MLFOW_TRACKING_URI_MYSQL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db.c7i2eagsgmtj.ap-south-1.rds.amazonaws.com:3306/${MYSQL_DATABASE}
    # command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0
    command: mlflow server --backend-store-uri ${MLFOW_TRACKING_URI_MYSQL} --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0
            # mlflow server --backend-store-uri mysql+pymysql://admin:Sun1@moon2@localhost:3306/db --default-artifact-root file:///home/user/mlflow_artifacts --host 0.0.0.0

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  artifacts:
  logs:
  mlruns:
