version: '3.8'

services:
  frauddetection:
    image: frauddetection:v1
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports:
      - "5000:5000"
    environment:
      MLFLOW_EXPERIMENT_NAME: exp-frauddetect
    volumes:
      - ./mlruns.db:/app/mlruns.db
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  local_artifacts:
  mlflow:
