stages:
  data_ingestion:
    cmd: python src/fraudDetection/components/data_ingestion.py
    deps:
      - src/fraudDetection/components/data_ingestion.py
      - configs/config.yaml 

  data_validation:
    cmd: python src/fraudDetection/components/data_validation.py
    deps: 
      - src/fraudDetection/components/data_validation.py
      - configs/config.yaml
      - configs/schema.yaml
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python src/fraudDectection/components/data_transformation.py
    deps:
      - src/fraudDectection/components/data_transformation.py
      - configs/config.yaml
    outs:
      - artifacts/transformed_dir/preprocessed/preprocessed.pkl
      - artifacts/transformed_dir/preprocessed/imputer_sampler.pkl

  model_trainer: 
    cmd: python src/fraudDetection/components/model_trainer.py
    deps:
      - src/fraudDetection/components/model_trainer.py
      - configs/config.yaml
      - configs/schema.yaml
      - configs/model.yaml
    params:
      # - threshold # track specific param (from params.yaml)
      - model.yaml: # track all parameters in this file
      - configs/config.yaml:
          - base_accuracy
          - threshold_diff_train_test_acc
    outs:
      - artifacts/model_trainer