stages:
  data_ingestion:
    cmd: python src/fraudDetection/components/training/data_ingestion.py
    deps:
      - src/fraudDetection/components/training/data_ingestion.py
      - configs/config.yaml 
      - src/fraudDetection/config/configuration.py
  
  data_validation:
    cmd: python src/fraudDetection/components/training/data_validation.py
    deps: 
      - src/fraudDetection/components/training/data_validation.py
      - configs/config.yaml
      - configs/schema.yaml

  data_transformation:
    cmd: python src/fraudDetection/components/training/data_transformation.py
    deps:
      -  src/fraudDetection/components/training/data_transformation.py
      - configs/config.yaml

  model_trainer: 
    cmd: python src/fraudDetection/components/training/model_trainer.py
    deps:
      - src/fraudDetection/components/training/model_trainer.py
      - src/fraudDetection/entity/model_factory.py
      - configs/config.yaml
      - configs/schema.yaml
      - configs/model.yaml
 
  model_evaluation: 
    cmd: python src/fraudDetection/components/training/model_evaluation.py
    deps: 
      - src/fraudDetection/components/training/model_evaluation.py

  model_pusher: 
    cmd: python src/fraudDetection/components/training/model_pusher.py
    deps:
      - src/fraudDetection/components/training/model_pusher.py
  
  pipeline:
    cmd: python src/fraudDetection/pipeline/pipeline.py
    deps:
      - src/fraudDetection/pipeline/pipeline.py