training_pipeline_config:
  pipeline_name: FraudDetection
  artifacts_root: artifacts

data_ingestion_config:
  source_url: kaggle datasets download -d rupakroy/online-payments-fraud-detection-dataset
  raw_data_dir: raw_data
  zip_dir: zip_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test
  stratify: isFraud
  test_size: 0.8
  
data_validation_config:
  schema_dir: configs
  schema_file_name: schema.yaml
  report_file_name: report.json
  report_file_dir: driftReport

data_transformation_config:
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl
  imputer_sampler_object_file_name: imputer_sampler.pkl

model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: configs
  model_config_file_name: model.yaml
  threshold_diff_train_test_acc: 0.3
  
model_evaluation_config:
  model_evaluation_dir: model_evaluation
  model_evaluation_file_name: model_evaluation.yaml
  mlflow_uri: 
  
model_pusher_config:
  model_export_dir: saved_models


  