grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 10
    n_jobs: -1
    verbose: 2
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      class_weight: balanced
      fit_intercept: true
      max_iter: 1000
    search_param_grid:
      penalty:
      - l2
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      bootstrap: true
      # min_samples_leaf: 3
    search_param_grid:
      class_weight:
      - balanced_subsample
      max_leaf_nodes:
      - 6
      random_state:
      - 42
