grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params: 
    cv: 10
    verbose: 2
    n_jobs: -1

model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params: 
      fit_intercept: true
      class_weight: balanced
      max_iter: 1000
    search_param_grid:
      penalty: 
        - l2

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      bootstrap: true
    search_param_grid:
      class_weight:
        - balanced_subsample
      oob_score:
        - true
      random_state:
        - 42
      max_leaf_nodes:
        - 6

  module_2:
    class: LinearSVC
    module: sklearn.svm
    params:
      dual: false
      class_weight: {0:1, 1:10}
      random_state: 42
    search_param_grid:
      class_weight: 
        - balanced
        
