# Schema Configuration

# Define the columns with their data types
columns:
  step: int64
  type: object
  amount: float64
  oldbalanceOrg: float64
  newbalanceOrig: float64
  oldbalanceDest: float64
  newbalanceDest: float64
  isFraud: int64

# Categorical columns in the dataset
categorical_columns:
  - type

# Numerical columns in the dataset
numerical_columns:
  - step
  - amount
  - oldbalanceOrg
  - newbalanceOrig
  - oldbalanceDest
  - newbalanceDest

# Target column for model training
target_column:
  - isFraud
