columns:
  step: int64
  type: object
  amount: float64
  oldbalanceOrg: float64
  newbalanceOrig: float64
  oldbalanceDest:  float64
  newbalanceDest:  float64
  isFraud: int64

categorical_columns: 
  - type

numerical_columns:
  - step
  - amount
  - oldbalanceOrg
  - newbalanceOrig
  - oldbalanceDest
  - newbalanceDest

target_column:
 - isFraud