from fraudDetection.components.data_ingestion import DataIngestion
from fraudDetection.components.data_validation import DataValidation
from fraudDetection.components.data_transformation import DataTransformation